x = system('dx ls -l .Backups',intern = T)
(x <- x[grepl('tar.gz \\(file-',x,T)])
timep = '[0-9]{4}-[0-9]{1,2}-[0-9]{1,2} {0,}[0-9]{1,2}:[0-9]{1,2}:[0-9]{1,2}'
wh = grep(timep,x)
(x1 = x[wh])
(x2 = gsub('.tar.gz \\(file-.*','',x1))
x2 = sub(' ','jjjjjjiiii',x2)
(x3=sub('.*jjjjjjiiii {0,}','',x2))
(x4 = sub(' {1,}','jjjjjjiiii',x3))
(x4=sub(' .*','',x4))
(x4=sub('jjjjjjiiii',' ',x4))
(wh = which.max(as.POSIXct(x4)))
(x3 = gsub('.*\\(','',x1[wh]))
(x3=gsub('\\)','',x3))
system(paste0("dx-restore-folder ",x3))
